#!/bin/bash
set -e

DATADIR="/data/.auroracoin"
CONF="$DATADIR/auroracoin.conf"

mkdir -p "$DATADIR"

if [ ! -f "$CONF" ]; then
  cat > "$CONF" <<EOF
# Auroracoin Node — auto-generated by Umbrel app

# Network
port=12340
rpcport=12341
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0

# Auth
rpcuser=${RPC_USER:-umbrel}
rpcpassword=${RPC_PASSWORD:-changeme}

# Pruning (~1GB, set prune=0 for full archival node)
prune=1024

# Performance
dbcache=256
maxmempool=64

# Enable RPC server
server=1

# Known AUR peers (official seeds are offline)
addnode=104.236.13.120
addnode=178.62.202.79
addnode=178.62.5.211
EOF
  echo "[entrypoint] Config written to $CONF"
fi

exec "$@"
